version: "3.9"
name: minecraft-on-docker
services:
  minecraft-server:
    container_name: minecraft-server
    image: ghcr.io/iamryusei/minecraft-on-docker:alpha
    env_file: minecraft.conf
    volumes:
      - ./data/world:/opt/minecraft/world
      - ./data/config:/opt/minecraft/config
      - ./data/config/EasyAuth:/opt/minecraft/mods/EasyAuth
      - ./data/logs:/opt/minecraft/logs
    ports:
      - "25565:25565"